# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "cloud-ui-checkout"
client_id = "ffa9d63909d7562dfd69272cf664e384"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
dev_store_url = "ga4-development.myshopify.com"
